import React, { createContext, useState, useContext, useEffect } from 'react';

type Language = 'pt-BR' | 'en-US' | 'es-ES' | 'fr-FR' | 'de-DE';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    'settings.title': 'Configurações',
    'settings.personalize': 'Personalize sua experiência no FocusCore',
    'settings.profile': 'Perfil',
    'settings.updatePersonal': 'Atualize suas informações pessoais',
    'settings.yourName': 'Seu nome',
    'settings.update': 'Atualizar',
    'settings.userId': 'ID do usuário',
    'settings.userIdDesc': 'Este ID é usado para identificar seus dados localmente.',
    'settings.sync': 'Sincronização Mobile',
    'settings.syncDesc': 'Exporte e importe seus dados entre dispositivos',
    'settings.syncText': 'Você pode transferir seus dados entre diferentes dispositivos exportando um arquivo de backup e importando-o em outro dispositivo onde o FocusCore esteja instalado.',
    'settings.exportData': 'Exportar Dados',
    'settings.importData': 'Importar Dados',
    'settings.mobileUse': 'Para usar o app como aplicativo nativo em seu smartphone:',
    'settings.appearance': 'Aparência',
    'settings.customizeTheme': 'Personalize o tema visual',
    'settings.darkMode': 'Modo escuro',
    'settings.enabled': 'Ativado',
    'settings.disabled': 'Desativado',
    'settings.language': 'Idioma',
    'settings.languageDesc': 'Selecione o idioma do aplicativo',
    'settings.reset': 'Redefinir dados',
    'settings.clearData': 'Limpar todos os dados salvos',
    'settings.resetAll': 'Redefinir todos os dados',
    'settings.confirmation': 'Você tem certeza?',
    'settings.confirmationDesc': 'Esta ação não pode ser desfeita. Isso irá apagar permanentemente todas as suas tarefas, hábitos e rotinas salvos neste dispositivo.',
    'settings.cancel': 'Cancelar',
    'settings.confirm': 'Sim, apagar tudo',
    'settings.localData': 'Todos os dados são armazenados apenas no seu dispositivo.',
    'nav.back': 'Voltar',
    'languages.pt': 'Português (Brasil)',
    'languages.en': 'English (US)',
    'languages.es': 'Español',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'app.footer.about': 'Sobre o FocusCore',
    'app.footer.privacy': 'Política de Privacidade',
    'app.footer.terms': 'Termos de Uso',
    'app.footer.copyright': 'Todos os direitos reservados',
    'app.nav.dashboard': 'Painel',
    'app.nav.tasks': 'Tarefas',
    'app.nav.habits': 'Hábitos',
    'app.nav.routines': 'Rotinas',
    'app.nav.financial': 'Finanças',
    'app.nav.calendar': 'Calendário',
    'app.nav.settings': 'Configurações',
    '404.title': '404',
    '404.message': 'Ops! Página não encontrada',
    '404.return': 'Voltar para a página inicial',
    'calendar.title': 'Calendário',
    'calendar.monthly': 'Calendário Mensal',
    'calendar.dayInfo': 'Informações do Dia',
    'calendar.selectedDate': 'Data selecionada',
    'calendar.holiday': 'Feriado',
    'calendar.nationalHoliday': 'Feriado Nacional',
    'calendar.regionalHoliday': 'Feriado Regional',
    'calendar.selectPrompt': 'Selecione uma data no calendário para ver mais informações',
  },
  'en-US': {
    'settings.title': 'Settings',
    'settings.personalize': 'Customize your FocusCore experience',
    'settings.profile': 'Profile',
    'settings.updatePersonal': 'Update your personal information',
    'settings.yourName': 'Your name',
    'settings.update': 'Update',
    'settings.userId': 'User ID',
    'settings.userIdDesc': 'This ID is used to identify your data locally.',
    'settings.sync': 'Mobile Sync',
    'settings.syncDesc': 'Export and import your data between devices',
    'settings.syncText': 'You can transfer your data between different devices by exporting a backup file and importing it on another device where FocusCore is installed.',
    'settings.exportData': 'Export Data',
    'settings.importData': 'Import Data',
    'settings.mobileUse': 'To use the app as a native application on your smartphone:',
    'settings.appearance': 'Appearance',
    'settings.customizeTheme': 'Customize the visual theme',
    'settings.darkMode': 'Dark mode',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.language': 'Language',
    'settings.languageDesc': 'Select application language',
    'settings.reset': 'Reset Data',
    'settings.clearData': 'Clear all saved data',
    'settings.resetAll': 'Reset all data',
    'settings.confirmation': 'Are you sure?',
    'settings.confirmationDesc': 'This action cannot be undone. This will permanently delete all your tasks, habits, and routines saved on this device.',
    'settings.cancel': 'Cancel',
    'settings.confirm': 'Yes, delete everything',
    'settings.localData': 'All data is stored only on your device.',
    'nav.back': 'Back',
    'languages.pt': 'Português (Brasil)',
    'languages.en': 'English (US)',
    'languages.es': 'Español',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'app.footer.about': 'About FocusCore',
    'app.footer.privacy': 'Privacy Policy',
    'app.footer.terms': 'Terms of Use',
    'app.footer.copyright': 'All rights reserved',
    'app.nav.dashboard': 'Dashboard',
    'app.nav.tasks': 'Tasks',
    'app.nav.habits': 'Habits',
    'app.nav.routines': 'Routines',
    'app.nav.financial': 'Financial',
    'app.nav.calendar': 'Calendar',
    'app.nav.settings': 'Settings',
    '404.title': '404',
    '404.message': 'Oops! Page not found',
    '404.return': 'Return to Home',
    'calendar.title': 'Calendar',
    'calendar.monthly': 'Monthly Calendar',
    'calendar.dayInfo': 'Day Information',
    'calendar.selectedDate': 'Selected date',
    'calendar.holiday': 'Holiday',
    'calendar.nationalHoliday': 'National Holiday',
    'calendar.regionalHoliday': 'Regional Holiday',
    'calendar.selectPrompt': 'Select a date in the calendar to see more information',
  },
  'es-ES': {
    'settings.title': 'Configuración',
    'settings.personalize': 'Personalice su experiencia en FocusCore',
    'settings.profile': 'Perfil',
    'settings.updatePersonal': 'Actualice su información personal',
    'settings.yourName': 'Su nombre',
    'settings.update': 'Actualizar',
    'settings.userId': 'ID de usuario',
    'settings.userIdDesc': 'Este ID se utiliza para identificar sus datos localmente.',
    'settings.sync': 'Sincronización Móvil',
    'settings.syncDesc': 'Exporte e importe sus datos entre dispositivos',
    'settings.syncText': 'Puede transferir sus datos entre diferentes dispositivos exportando un archivo de respaldo e importándolo en otro dispositivo donde FocusCore esté instalado.',
    'settings.exportData': 'Exportar Datos',
    'settings.importData': 'Importar Datos',
    'settings.mobileUse': 'Para usar la aplicación como aplicación nativa en su smartphone:',
    'settings.appearance': 'Apariencia',
    'settings.customizeTheme': 'Personalice el tema visual',
    'settings.darkMode': 'Modo oscuro',
    'settings.enabled': 'Activado',
    'settings.disabled': 'Desactivado',
    'settings.language': 'Idioma',
    'settings.languageDesc': 'Seleccione el idioma de la aplicación',
    'settings.reset': 'Restablecer datos',
    'settings.clearData': 'Borrar todos los datos guardados',
    'settings.resetAll': 'Restablecer todos los datos',
    'settings.confirmation': '¿Está seguro?',
    'settings.confirmationDesc': 'Esta acción no se puede deshacer. Esto eliminará permanentemente todas sus tareas, hábitos y rutinas guardadas en este dispositivo.',
    'settings.cancel': 'Cancelar',
    'settings.confirm': 'Sí, borrar todo',
    'settings.localData': 'Todos los datos se almacenan solo en su dispositivo.',
    'nav.back': 'Volver',
    'languages.pt': 'Português (Brasil)',
    'languages.en': 'English (US)',
    'languages.es': 'Español',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'app.footer.about': 'Acerca de FocusCore',
    'app.footer.privacy': 'Política de Privacidad',
    'app.footer.terms': 'Términos de Uso',
    'app.footer.copyright': 'Todos los derechos reservados',
    'app.nav.dashboard': 'Panel',
    'app.nav.tasks': 'Tareas',
    'app.nav.habits': 'Hábitos',
    'app.nav.routines': 'Rutinas',
    'app.nav.financial': 'Finanzas',
    'app.nav.calendar': 'Calendario',
    'app.nav.settings': 'Configuración',
    '404.title': '404',
    '404.message': '¡Ups! Página no encontrada',
    '404.return': 'Volver a la página principal',
    'calendar.title': 'Calendario',
    'calendar.monthly': 'Calendario Mensual',
    'calendar.dayInfo': 'Información del Día',
    'calendar.selectedDate': 'Fecha seleccionada',
    'calendar.holiday': 'Festivo',
    'calendar.nationalHoliday': 'Festivo Nacional',
    'calendar.regionalHoliday': 'Festivo Regional',
    'calendar.selectPrompt': 'Seleccione una fecha en el calendario para ver más información',
  },
  'fr-FR': {
    'settings.title': 'Paramètres',
    'settings.personalize': 'Personnalisez votre expérience FocusCore',
    'settings.profile': 'Profil',
    'settings.updatePersonal': 'Mettez à jour vos informations personnelles',
    'settings.yourName': 'Votre nom',
    'settings.update': 'Mettre à jour',
    'settings.userId': 'ID utilisateur',
    'settings.userIdDesc': 'Cet ID est utilisé pour identifier vos données localement.',
    'settings.sync': 'Synchronisation Mobile',
    'settings.syncDesc': 'Exportez et importez vos données entre appareils',
    'settings.syncText': 'Vous pouvez transférer vos données entre différents appareils en exportant un fichier de sauvegarde et en l\'important sur un autre appareil où FocusCore est installé.',
    'settings.exportData': 'Exporter les données',
    'settings.importData': 'Importer les données',
    'settings.mobileUse': 'Pour utiliser l\'application comme application native sur votre smartphone:',
    'settings.appearance': 'Apparence',
    'settings.customizeTheme': 'Personnalisez le thème visuel',
    'settings.darkMode': 'Mode sombre',
    'settings.enabled': 'Activé',
    'settings.disabled': 'Désactivé',
    'settings.language': 'Langue',
    'settings.languageDesc': 'Sélectionnez la langue de l\'application',
    'settings.reset': 'Réinitialiser les données',
    'settings.clearData': 'Effacer toutes les données enregistrées',
    'settings.resetAll': 'Réinitialiser toutes les données',
    'settings.confirmation': 'Êtes-vous sûr?',
    'settings.confirmationDesc': 'Cette action ne peut pas être annulée. Cela supprimera définitivement toutes vos tâches, habitudes et routines enregistrées sur cet appareil.',
    'settings.cancel': 'Annuler',
    'settings.confirm': 'Oui, tout supprimer',
    'settings.localData': 'Toutes les données sont stockées uniquement sur votre appareil.',
    'nav.back': 'Retour',
    'languages.pt': 'Português (Brasil)',
    'languages.en': 'English (US)',
    'languages.es': 'Español',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'app.footer.about': 'À propos de FocusCore',
    'app.footer.privacy': 'Politique de Confidentialité',
    'app.footer.terms': 'Conditions d\'Utilisation',
    'app.footer.copyright': 'Tous droits réservés',
    'app.nav.dashboard': 'Tableau de bord',
    'app.nav.tasks': 'Tâches',
    'app.nav.habits': 'Habitudes',
    'app.nav.routines': 'Routines',
    'app.nav.financial': 'Finances',
    'app.nav.calendar': 'Calendrier',
    'app.nav.settings': 'Paramètres',
    '404.title': '404',
    '404.message': 'Oups! Page non trouvée',
    '404.return': 'Retourner à l\'accueil',
    'calendar.title': 'Calendrier',
    'calendar.monthly': 'Calendrier Mensuel',
    'calendar.dayInfo': 'Informations du Jour',
    'calendar.selectedDate': 'Date sélectionnée',
    'calendar.holiday': 'Jour férié',
    'calendar.nationalHoliday': 'Jour férié national',
    'calendar.regionalHoliday': 'Jour férié régional',
    'calendar.selectPrompt': 'Sélectionnez une date dans le calendrier pour voir plus d\'informations',
  },
  'de-DE': {
    'settings.title': 'Einstellungen',
    'settings.personalize': 'Passen Sie Ihr FocusCore-Erlebnis an',
    'settings.profile': 'Profil',
    'settings.updatePersonal': 'Aktualisieren Sie Ihre persönlichen Daten',
    'settings.yourName': 'Ihr Name',
    'settings.update': 'Aktualisieren',
    'settings.userId': 'Benutzer-ID',
    'settings.userIdDesc': 'Diese ID wird verwendet, um Ihre Daten lokal zu identifizieren.',
    'settings.sync': 'Mobile Synchronisierung',
    'settings.syncDesc': 'Exportieren und importieren Sie Ihre Daten zwischen Geräten',
    'settings.syncText': 'Sie können Ihre Daten zwischen verschiedenen Geräten übertragen, indem Sie eine Sicherungsdatei exportieren und auf einem anderen Gerät importieren, auf dem FocusCore installiert ist.',
    'settings.exportData': 'Daten exportieren',
    'settings.importData': 'Daten importieren',
    'settings.mobileUse': 'Um die App als native Anwendung auf Ihrem Smartphone zu verwenden:',
    'settings.appearance': 'Aussehen',
    'settings.customizeTheme': 'Passen Sie das visuelle Thema an',
    'settings.darkMode': 'Dunkler Modus',
    'settings.enabled': 'Aktiviert',
    'settings.disabled': 'Deaktiviert',
    'settings.language': 'Sprache',
    'settings.languageDesc': 'Wählen Sie die Anwendungssprache',
    'settings.reset': 'Daten zurücksetzen',
    'settings.clearData': 'Alle gespeicherten Daten löschen',
    'settings.resetAll': 'Alle Daten zurücksetzen',
    'settings.confirmation': 'Sind Sie sicher?',
    'settings.confirmationDesc': 'Diese Aktion kann nicht rückgängig gemacht werden. Dadurch werden alle Ihre auf diesem Gerät gespeicherten Aufgaben, Gewohnheiten und Routinen dauerhaft gelöscht.',
    'settings.cancel': 'Abbrechen',
    'settings.confirm': 'Ja, alles löschen',
    'settings.localData': 'Alle Daten werden nur auf Ihrem Gerät gespeichert.',
    'nav.back': 'Zurück',
    'languages.pt': 'Português (Brasil)',
    'languages.en': 'English (US)',
    'languages.es': 'Español',
    'languages.fr': 'Français',
    'languages.de': 'Deutsch',
    'app.footer.about': 'Über FocusCore',
    'app.footer.privacy': 'Datenschutzrichtlinie',
    'app.footer.terms': 'Nutzungsbedingungen',
    'app.footer.copyright': 'Alle Rechte vorbehalten',
    'app.nav.dashboard': 'Dashboard',
    'app.nav.tasks': 'Aufgaben',
    'app.nav.habits': 'Gewohnheiten',
    'app.nav.routines': 'Routinen',
    'app.nav.financial': 'Finanzen',
    'app.nav.calendar': 'Kalender',
    'app.nav.settings': 'Einstellungen',
    '404.title': '404',
    '404.message': 'Hoppla! Seite nicht gefunden',
    '404.return': 'Zurück zur Startseite',
    'calendar.title': 'Kalender',
    'calendar.monthly': 'Monatskalender',
    'calendar.dayInfo': 'Tagesinformationen',
    'calendar.selectedDate': 'Ausgewähltes Datum',
    'calendar.holiday': 'Feiertag',
    'calendar.nationalHoliday': 'Nationaler Feiertag',
    'calendar.regionalHoliday': 'Regionaler Feiertag',
    'calendar.selectPrompt': 'Wählen Sie ein Datum im Kalender, um weitere Informationen zu sehen',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('focuscore-language');
    return (savedLanguage as Language) || 'pt-BR';
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('focuscore-language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
